### ISSUE TITLE
GitHub Action upload-artifact@v3 will stop working on 2025-01-30

### ISSUE THREAD

**Issue by jfpanisset** [AcademySoftwareFoundation/artwork#49]
As per [Deprecation notice: v3 of the artifact actions](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) the GitHub Action
upload-artifact@v3 used in .github/workflows/jekyll.yml will stop working on 2025-01-30n and must be replaced by @v4 before that deadline.

**Comment by jmertic** [comment]
Closing with #50 - though I will note that `upload-artifact` is the affected action, while the one used here `upload-pages-artifact` which isn't affected.
